teaching/teaching/urls.py
from django.contrib import admin
from django.urls import path,include
from teaching_app.views import index,UserLogin,UserLogout

urlpatterns = [
    path('admin/', admin.site.urls),
    path('teaching_app/',include('teaching_app.urls')),
    path('',index,name='index'),
    path('login/',UserLogin,name='login'),
    path('logout/',UserLogout,name='logout'),
]

teaching/teaching_app/urls.py
from django.urls import path
from .views import UserInfoView

app_name = 'teaching_app'

urlpatterns = [
    path('register/',UserInfoView,name='register'),
]

teaching/teaching_app/models.py
from django.db import models
from django.contrib.auth.models import User

class UserModel(models.Model):

    user = models.OneToOneField(User,on_delete=models.CASCADE)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

teaching/teaching_app/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserModel


class UserModelForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username','email','password']

class UserModelExtraForm(forms.ModelForm):
    class Meta:
        model = UserModel
        fields = ['profile_pic']

teaching/teaching_app/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import login,logout,authenticate
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
# relative import
from .forms import UserModelForm,UserModelExtraForm


def index(request):
    return render(request,'teaching_app/index.html')

def UserInfoView(request):

    registered = False

    if request.method == 'POST':

        usermodel = UserModelForm(request.POST)
        usermodelextra = UserModelExtraForm(request.POST)

        if usermodel.is_valid() and usermodelextra.is_valid():

            user = usermodel.save()
            user.set_password(user.password)
            user.save()

            profile = usermodelextra.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()
            registered = True

    else:
        usermodel = UserModelForm()
        usermodelextra = UserModelExtraForm()

    context = {
        'usermodel' : usermodel,
        'usermodelextra' : usermodelextra,
        'registered' : registered,
    }

    return render(request,'teaching_app/register.html',context)



def UserLogin(request):

    if request.method == 'POST':

        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return redirect('../')

            else:
                return HttpResponse('Not active')

        else:
            return HttpResponse('Invalid Username or Password')

    else:
        return render(request,'teaching_app/login.html')


@login_required
def UserLogout(request):
    logout(request)
    return redirect('../')

teaching/templates/teaching_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Base</title>
  </head>
  <body>
    <nav>
      <ul>
        <li><a href="{% url 'index' %}">Index</a></li>
        <li><a href="{% url 'teaching_app:register' %}">Register</a></li>
        <li><a href="{% url 'admin:index' %}">Admin</a></li>

        {% if user.is_authenticated %}
          <li><a href="{% url 'logout' %}">Logout</a></li>
        {% else %}
          <li><a href="{% url 'login' %}">Login</a></li>
        {% endif %}
        
      </ul>
    </nav>

    {% block content %}
    {% endblock %}
  </body>
</html>

teaching/templates/teaching_app/index.html
{% extends 'teaching_app/base.html'%}

{% block content %}
  <h2>Welcome to Index page</h2>
{% endblock %}

teaching/templates/teaching_app/login.html
{% extends 'teaching_app/base.html' %}

{% block content %}

  <h2>Login Here!</h2>
  <form method="post">
    {% csrf_token %}

    <label for="username">Username</label>
    <input type="text" name="username" placeholder="Enter Username">

    <label for="password">Password</label>
    <input type="password" name="password">

    <input type="submit" value="Login">
  </form>

{% endblock %}

teaching/templates/teaching_app/register.html
{% extends 'teaching_app/base.html'%}

{% block content %}

  {% if registered %}
    <h2>Successful in registering</h2>

  {% else %}
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ usermodel.as_p }}
      {{ usermodelextra.as_p }}
      <input type="submit" value="Register">
    </form>

  {% endif %}

{% endblock %}